# Generated by Django 4.2.1 on 2023-05-10 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientportion',
            name='amount',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Мин.кол-во - 1')], verbose_name='Количество'),
        ),
    ]
