# Generated by Django 4.2.1 on 2023-05-19 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_cart_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredientportion',
            name='amount',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Мин.кол-во ингредиента -1'), django.core.validators.MaxValueValidator(1000, message='Мин.кол-во ингредиента - 1000')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Цветовой HEX-код'),
        ),
    ]
