# Generated by Django 4.2.1 on 2023-05-11 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('id',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Мин.время - 1 минута')], verbose_name='Время приготовления в минутах'),
            preserve_default=False,
        ),
    ]
